spring.datasource.url=jdbc:postgresql://ep-rough-wildflower-b5l3qpm7-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_6R8JPZmbBepn
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

jwt.secret=RmlzaW90ZXJhcGlhTGlzdGFEZVByZXNlbmNhSldUU2VjcmV0S2V5MjAyNiE=
jwt.expiration=3600000